### ISSUE TITLE
ESTree.Tools.Builder.identifier/1 not found

### ISSUE THREAD

**Issue by olgeni** [bryanjos/elixirscript#72]
Hi,

When trying to process the example "Lions.Tigers.Bears" with version 0.6.5 I get this error:

```
** (UndefinedFunctionError) undefined function: ESTree.Tools.Builder.identifier/1 (module ESTree.Tools.Builder is not available)
    ESTree.Tools.Builder.identifier(:Bears)
    (elixir_script) lib/elixir_script/translator/utils.ex:102: ElixirScript.Translator.Utils.make_member_expression/3
    (elixir_script) lib/elixir_script/translator/utils.ex:67: ElixirScript.Translator.Utils.make_call_expression/3
    (elixir_script) lib/elixir_script/translator/module.ex:59: ElixirScript.Translator.Module.make_module/2
    (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:977: Enum.map/2
    (elixir_script) lib/elixir_script.ex:65: ElixirScript.transpile_path/2
```

Apparently I only have identifier/2 in my code path.

```
iex(1)> ESTree.Tools.Builder.identifier [tab]
identifier/2
```

I have estree 2.0.0 and inflex 1.4.0 installed.

Do you have any pointers that could help me track this down?

**Comment by bryanjos** [comment]
That's correct that only identifier/2 exists. The second parameter is optional. I haven't been able to reproduce it, but I'll give it a shot when I get a chance to later in the day.

**Comment by bryanjos** [comment]
I still haven't been able to reproduce the issue. Could you share the elixir code you are trying to transpile so that I can see if I can reproduce it with that?

**Comment by olgeni** [comment]
It goes like this, with the example code:

```
$ cat hello.ex
defmodule Hello do
    Lions.Tigers.Bears.oh_my(true)
end

$ ex2js -o hello.js hello.ex
** (UndefinedFunctionError) undefined function: ESTree.Tools.Builder.identifier/1 (module ESTree.Tools.Builder is not available)
    ESTree.Tools.Builder.identifier(:Bears)
    (elixir_script) lib/elixir_script/translator/utils.ex:102: ElixirScript.Translator.Utils.make_member_expression/3
    (elixir_script) lib/elixir_script/translator/utils.ex:67: ElixirScript.Translator.Utils.make_call_expression/3
    (elixir_script) lib/elixir_script/translator/module.ex:59: ElixirScript.Translator.Module.make_module/2
    (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:977: Enum.map/2
    (elixir_script) lib/elixir_script.ex:65: ElixirScript.transpile_path/2
```

First time I'm trying this out, so maybe I'm missing some step?

**Comment by bryanjos** [comment]
I just tried with the version from master, the release one, and using it via the version in hex and it transpiled hello.ex successfully each time.

Looking at that error though makes me think it has something to do with the version of ESTree. But if it's 2.0.0 then it should work.

If you are using it in an Elixir project, you can try the following below in iex and see if you get the same result

```elixir
ElixirScript.transpile("""
  defmodule Hello do
    Lions.Tigers.Bears.oh_my(true)
  end
""")
```

**Comment by olgeni** [comment]
This seems to work just fine:

```
Interactive Elixir (1.0.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> ElixirScript.transpile("""
...(1)>   defmodule Hello do
...(1)>     Lions.Tigers.Bears.oh_my(true)
...(1)>   end
...(1)> """)
["import Erlang from '__lib/erlang';\nimport Kernel from '__lib/kernel';\nimport Bears from 'lions/tigers/bears';\nconst __MODULE__ = Erlang.atom('Hello');\nBears.oh_my(true);\nexport default {};"]
iex(2)>
```
Maybe there's something weird on my JavaScript side - I'll try to look into it.

**Comment by olgeni** [comment]
Fixed - code path issues on my side, while building the escript part. Everything's ok now - thanks!

**Comment by bryanjos** [comment]
Awesome!
